### PR TITLE
Weeks

### PR DESCRIPTION
**Pull request by narimiran**
Solves issue #3 .

~~TODO: write new tests~~

### CODE REVIEW

**Comment by aaugustin** [comment]
Hello! Thanks for the pull request!

In #3 I wrote that I didn't see the need for adding `weeks` to the datedelta constructor because there's no special logic associated with them. I thought the `WEEK` constant would be enough and I wasn't even sure it would be useful — that's why I created an issue instead of making the one-line change. What would be the arguments for adding `weeks` to the constructor?

If I were to add them, I'd just do `self._days = days + 7 * weeks`. Otherwise you have multiple representations of the same value. For example `datedelta(days=6)` is exactly the same as `datedelta(weeks=1, days=-1)` but they don't compare equal in your pull request.

You seem to have put a significant effort into this patch; I'm sorry we didn't talk before you started :-/

**Comment by narimiran** [comment]
> In #3 I wrote that I didn't see the need for adding weeks to the datedelta constructor because there's no special logic associated with them.

...and I misread what you have written/meant :)

> What would be the arguments for adding weeks to the constructor?

Don't know, but I'll try hard to come up with something :D 

> You seem to have put a significant effort into this patch; I'm sorry we didn't talk before you started :-/

Well, I had some free time to spare, and it was a good exercise for me.

**Comment by aaugustin** [comment]
Okay. Sorry again if #3 was unclear and confused you!

**Comment by narimiran** [comment]
Btw, I was thinking about this:

> For example `datedelta(days=6)` is exactly the same as `datedelta(weeks=1, days=-1)` but they don't compare equal in your pull request.

The same thing happens with `datedelta(years=1)` and `datedelta(months=12)`. When you add them to some date, they give you the same final date, but they don't compare equal.

Should `__eq__` be changed to accommodate this or not?

**Comment by aaugustin** [comment]
This is true.

However there are accidental complexities in this area. For not entirely obvious reasons, `datedelta(years=4)` and `datedelta(years=2, months=24)` return different result when added to a Feb 29th.

So it may be easier to keep the equality rule dead simple, at the cost of marking as unequal some values that are actually equal.

**Pull request closed without merging**
